<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ColdNet.Core\ColdNet.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.2" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
