// <auto-generated />
using System;
using System.Collections.Generic;
using ColdNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdNet.Data.Migrations
{
    [DbContext(typeof(ColdNetDbContext))]
    [Migration("20260917085329_AddJobLogEntry")]
    partial class AddJobLogEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ColdNet.Core.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentModuleOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErrorModuleOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessChainId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDirectory")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessChainId", "FilePrefix")
                        .IsUnique();

                    b.HasIndex("ProcessChainId", "Status", "CurrentModuleOrder");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("ColdNet.Core.Domain.JobLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "TimestampUtc");

                    b.ToTable("JobLogEntries", (string)null);
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ModuleInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessChainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CommonSettings", "ColdNet.Core.Domain.ModuleInstance.CommonSettings#CommonModuleSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Append")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Append");

                            b1.Property<bool>("DeleteSourceFile")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DeleteSourceFile");

                            b1.Property<string>("Directory")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Directory");

                            b1.Property<string>("FileExtension")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("FileExtension");

                            b1.Property<bool>("MaskForDms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaskForDms");

                            b1.Property<string>("OutputDirectory")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("OutputDirectory");

                            b1.Property<string>("OutputFileExtension")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("OutputFileExtension");

                            b1.Property<bool>("Save")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Save");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DmsSupport", "ColdNet.Core.Domain.ModuleInstance.DmsSupport#DmsSupportSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DocumentType")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("DmsDocumentType");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DmsSupportEnabled");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProcessChainId", "Order")
                        .IsUnique();

                    b.ToTable("ModuleInstances", (string)null);
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ProcessChain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsPerStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessGroupId");

                    b.HasIndex("WorkerName");

                    b.ToTable("ProcessChains", (string)null);
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ProcessGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessGroups", (string)null);
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ModuleInstance", b =>
                {
                    b.HasOne("ColdNet.Core.Domain.ProcessChain", null)
                        .WithMany("Modules")
                        .HasForeignKey("ProcessChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ProcessChain", b =>
                {
                    b.HasOne("ColdNet.Core.Domain.ProcessGroup", null)
                        .WithMany("Chains")
                        .HasForeignKey("ProcessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ProcessChain", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ColdNet.Core.Domain.ProcessGroup", b =>
                {
                    b.Navigation("Chains");
                });
#pragma warning restore 612, 618
        }
    }
}
