<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ColdNet.Core\ColdNet.Core.csproj" />
    <ProjectReference Include="..\ColdNet.Data\ColdNet.Data.csproj" />
    <ProjectReference Include="..\ColdNet.Modules\ColdNet.Modules.csproj" />
    <ProjectReference Include="..\ColdNet.EdmVault\ColdNet.EdmVault.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
